name: 'docker'
description: 'create docker build env'
inputs:
  fpm-recipe:
    description: 'Which FPM recipe to build'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker/bionic/Dockerfile'
  args:
    - ${{ inputs.fpm-recipe }}

  - name: Archive production artifact
    uses: actions/upload-artifact@v2
    with:
      path: ${{ inputs.fpm-recipe }}.deb