name: 'docker'
description: 'create docker build env'
inputs:
  fpm-recipe:
    description: 'Which FPM recipe to build'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: "composite"
  steps:
    - name: build ${{ inputs.fpm-recipe }}
      using: 'docker'
      image: 'docker/bionic/Dockerfile'
      args:
        - ${{ inputs.fpm-recipe }}
    - name: Archive .deb
      uses: actions/upload-artifact@v2
      with:
        path: '*.deb'